[package]
name = "csp"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version="^ 0.8.5", features=["small_rng"] }
rand_seeder = "^ 0.2.3"

[dev-dependencies]
serde_json = "1.0.120"
