[package]
name = "ac3-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version="^ 0.9.0", features=["small_rng"] }
rand_seeder = "^ 0.3.0"
ac3 = { path = "../ac3" }
