name: Release Management

permissions:
  pull-requests: write
  id-token: write
  contents: write

#env:
  # ALL_CARGO_DIST_TARGET_ARGS: --target=x86_64-unknown-linux-gnu --target=x86_64-apple-darwin --target=x86_64-pc-windows-msvc 
  # ALL_CARGO_DIST_INSTALLER_ARGS: ''

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: "release-please-config.json"
